inherit: true
filter:
    excluded_paths:
        - wp-content/*
        - wp-includes/ID3/*
        - wp-includes/SimplePie/*
        - wp-includes/Text/*
        - wp-includes/atomlib.php
        - wp-includes/class-IXR.php
        - wp-includes/class-json.php
        - wp-includes/class-phpass.php
        - wp-includes/class-phpmailer.php
        - wp-includes/class-pop3.php
        - wp-includes/class-simplepie.php
        - wp-includes/class-smtp.php
        - wp-includes/class-snoopy.php
        - wp-includes/rss.php
        - wp-admin/includes/class-ftp-pure.php
        - wp-admin/includes/class-ftp-sockets.php
        - wp-admin/includes/class-ftp.php
        - wp-admin/includes/class-pclzip.php
    paths: {  }
tools:
    php_code_sniffer:
        enabled: true
        extensions:
            - php

    php_cs_fixer:
        enabled: true
        extensions:
            - php

    php_mess_detector:
        enabled: true
        extensions:
            - php

    php_sim:
        enabled: true

    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }

    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        path_configs: {  }

    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'

    php_hhvm:
        enabled: true
        command: hhvm
        extensions:
            - php

        path_configs: {  }
before_commands: {  }
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }